# Generated by Django 3.2.9 on 2021-11-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('Type', models.CharField(choices=[('Discount By amount', 'Discount By Amount'), ('Discount By percentage', 'Discount By percentage')], max_length=30)),
                ('quantity', models.IntegerField(blank=True, default=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, default='Physical', max_length=20, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('subcategory', models.CharField(choices=[('Oats', 'Oats'), ('Muesli', 'Muesli'), ('Exotic Coffe', 'Exotic Coffe'), ('Mens Nutrition', 'Mens Nutrition'), ('Womens Nutrition', 'Womens Nutrition')], default='Oats', max_length=50)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages'), ('Grocery', 'Grocery'), ('Nutrition', 'Nutrition')], default='Breakfast', max_length=50)),
                ('discount', models.CharField(blank=True, choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40')], max_length=50, null=True)),
                ('Status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=20, null=True)),
                ('Stock', models.CharField(blank=True, choices=[('Unlimited', 'Unlimited'), ('Limited', 'Limited')], max_length=20, null=True)),
                ('Options', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Unlimited', 'Unlimited')], max_length=10, null=True)),
                ('Currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('INR', 'INR')], max_length=10, null=True)),
                ('Cost', models.IntegerField(blank=True, null=True)),
                ('Duration', models.CharField(choices=[('1-Year', '1-Year'), ('2-Year', '2-Year'), ('3-Year', '3-Year')], max_length=10)),
                ('ProductsAllowed', models.CharField(blank=True, choices=[('Unlimited', 'Unlimited'), ('Limited', 'Limited')], max_length=10, null=True)),
                ('PlanStatus', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Removed', 'Removed')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('shopName', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
