# Generated by Django 3.2.9 on 2021-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Oats', 'Oats'), ('Flour', 'Flour'), ('Muesli', 'Muesli'), ('Exotic Coffe', 'Exotic Coffe'), ('Mens Nutrition', 'Mens Nutrition'), ('Womens Nutrition', 'Womens Nutrition')], default='Oats', max_length=50),
        ),
    ]
