# Generated by Django 3.2.9 on 2021-11-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211124_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40')], max_length=20, null=True),
        ),
    ]
