# Generated by Django 3.2.9 on 2021-11-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211124_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages'), ('Grocery', 'Grocery'), ('Nutrition', 'Nutrition'), ('Organic Foods', 'Organic Foods'), ('Pet Lovers', 'Pet Lovers')], default='Breakfast', max_length=50),
        ),
    ]
