# Generated by Django 3.2.9 on 2021-11-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('INR', 'INR')], max_length=10, null=True)),
                ('sign', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
